### ISSUE TITLE
Just some recommendations 

### ISSUE THREAD

**Issue by behruzinomov** [bakhtiyor/leetcode-challenge#1]
Bakhtiyor-ako you are doing a great job solving every day one task. This will motivate everyone.

Just some recommendation maybe)

Bakhtiyor-ako isn't better to calculate $iMax = strlen($s); (I think row 44) before the loop one time and assign to another variable? Because in every loop this function calculates the same length.
You can correct me If im missed something or mistaken

**Comment by bakhtiyor** [comment]
Hi Behruz. Thanks for your compliment. Could you please give the link of the problem you are referring to?

**Comment by bakhtiyor** [comment]
I will close this issue as I didn't receive any reply to my question during the long time.
